name: Test
on: push
jobs:
  run-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install golang
        uses: actions/setup-go@v3
        with:
          go-version: "1.19"
      - name: Run static analysis
        uses: PiwikPRO/actions/go/lint@master
        with:
          go-version: "1.19"
      - name: Run tests
        run: make tests
